// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eombihjcafvwejycscdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvbWJpaGpjYWZ2d2VqeWNzY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzU0NzQsImV4cCI6MjA3NDQ1MTQ3NH0.Dc7EhmWxkwOvMLY5h2gbk0u1_IuC861j4iUKu1aJv2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});